### ISSUE TITLE
Issues with 1.8.8

### ISSUE THREAD

**Issue by ShaneBeee** [Tower-Defence/Beamer#1]
So I tried this on 1.12.2 and it works great. A Few people were telling me it doesn't work on 1.8 so I tested it. I used Skript Dev37c and I used the ProtocolLib version suggested on their resource page.
This is the error in 1.8.8

```[16:14:57 INFO]: ShaneBee [1748129a-525b-44eb-8fb5-8953d0287507]: /beam
[16:14:57 ERROR]: #!#! 
[16:14:57 ERROR]: #!#! [Skript] Severe Error:
[16:14:57 ERROR]: #!#! 
[16:14:57 ERROR]: #!#! Something went horribly wrong with Skript.
[16:14:57 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:14:57 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[16:14:57 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[16:14:57 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[16:14:57 ERROR]: #!#! nor it will work, unless you switch to supported platform.
[16:14:57 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[16:14:57 ERROR]: #!#! 
[16:14:57 ERROR]: #!#! Stack trace:
[16:14:57 ERROR]: #!#! FieldAccessException: No field with type java.util.UUID exists in class PacketPlayOutSpawnEntityLiving.
[16:14:57 ERROR]: #!#!     at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:363)
[16:14:57 ERROR]: #!#!     at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:343)
[16:14:57 ERROR]: #!#!     at net.jaxonbrown.guardianBeam.protocol.PacketFactory.createPacketSquidSpawn(PacketFactory.java:71)
[16:14:57 ERROR]: #!#!     at net.jaxonbrown.guardianBeam.beam.LocationTargetBeam.<init>(LocationTargetBeam.java:50)
[16:14:57 ERROR]: #!#!     at net.jaxonbrown.guardianBeam.beam.ClientBeam.<init>(ClientBeam.java:81)
[16:14:57 ERROR]: #!#!     at net.jaxonbrown.guardianBeam.beam.ClientBeam.<init>(ClientBeam.java:56)
[16:14:57 ERROR]: #!#!     at me.limeglass.beamer.elements.expressions.ExprNewBeam.get(ExprNewBeam.java:32)
[16:14:57 ERROR]: #!#!     at me.limeglass.beamer.elements.expressions.ExprNewBeam.get(ExprNewBeam.java:16)
[16:14:57 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[16:14:57 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:275)
[16:14:57 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[16:14:57 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[16:14:57 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[16:14:57 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[16:14:57 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:294)
[16:14:57 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[16:14:57 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:257)
[16:14:57 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:172)
[16:14:57 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:14:57 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:14:57 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:14:57 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[16:14:57 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:14:57 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:14:57 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:14:57 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:14:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[16:14:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[16:14:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:14:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:14:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:14:57 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:14:57 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:14:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:14:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:14:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:14:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:14:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:14:57 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[16:14:57 ERROR]: #!#! 
[16:14:57 ERROR]: #!#! Version Information:
[16:14:57 ERROR]: #!#!   Skript: 2.2-dev37c (latest)
[16:14:57 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[16:14:57 ERROR]: #!#!   Minecraft: 1.8.8
[16:14:57 ERROR]: #!#!   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
[16:14:57 ERROR]: #!#!   OS: Mac OS X x86_64 10.14
[16:14:57 ERROR]: #!#! 
[16:14:57 ERROR]: #!#! Server platform: Spigot
[16:14:57 ERROR]: #!#! 
[16:14:57 ERROR]: #!#! Current node: null
[16:14:57 ERROR]: #!#! Current item: set {_beam}(as java.lang.Object) to ExprNewBeam - [[a] [new] beam (between|from) %location% (to|and) %location% for %player% [[(with|in)] radius %-number% [and] update delay %-number%]]
[16:14:57 ERROR]: #!#! Current trigger: command /beam (simple event) (test.sk, line -1)
[16:14:57 ERROR]: #!#! 
[16:14:57 ERROR]: #!#! Thread: Server thread
[16:14:57 ERROR]: #!#! 
[16:14:57 ERROR]: #!#! Language: english
[16:14:57 ERROR]: #!#! Link parse mode: DISABLED
[16:14:57 ERROR]: #!#! 
[16:14:57 ERROR]: #!#! End of Error.
[16:14:57 ERROR]: #!#! 
```

**Comment by TheLimeGlass** [comment]
Fixed in 1.0.1
